version: '3'
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "5552-5554:4442-4444"  # Map external ports 5552-5554 to internal ports 4442-4444
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5552
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5553
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5552
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5553
    networks:
      - grid

networks:
  grid:
    driver: bridge

